name: Update ipban.txt

on:
  schedule:
    - cron: '0 0 1 * *' # This will run the first day of every month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run script
      run: |
        # Download the file
        wget https://github.com/DandelionSprout/adfilt/raw/master/AdGuardHomeDisallowedIPs.txt -O newfile.txt

        # Generate hash for the new file
        NEWFILE_HASH=$(sha256sum newfile.txt | awk '{ print $1 }')

        # Check if oldfile.txt exists
        if [ -f oldfile.txt ]; then
            # Generate hash for the old file
            OLDFILE_HASH=$(sha256sum oldfile.txt | awk '{ print $1 }')

            # Compare hashes
            if [ "$NEWFILE_HASH" = "$OLDFILE_HASH" ]; then
                echo "The files are the same. No updates."
                exit 0
            fi
        fi

        echo "The files are different. There are updates."

        # Remove unwanted texts and duplicates
        grep -Pv '^(!.*)?$' newfile.txt | sort | uniq > ipban.txt

        # Commit and push the changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ipban.txt
        git commit -m "Update ipban.txt"
        git push

        # Replace oldfile.txt with newfile.txt for the next comparison
        mv newfile.txt oldfile.txt
